# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'led_yakolacakmi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 541, 201))
        self.groupBox.setObjectName("groupBox")
        self.ComSelect = QtWidgets.QComboBox(self.groupBox)
        self.ComSelect.setGeometry(QtCore.QRect(30, 20, 421, 22))
        self.ComSelect.setAutoFillBackground(False)
        self.ComSelect.setObjectName("ComSelect")
        self.SerialBeginSelect = QtWidgets.QComboBox(self.groupBox)
        self.SerialBeginSelect.setGeometry(QtCore.QRect(30, 60, 421, 22))
        self.SerialBeginSelect.setObjectName("SerialBeginSelect")
        self.Baglan = QtWidgets.QPushButton(self.groupBox)
        self.Baglan.setGeometry(QtCore.QRect(30, 100, 421, 23))
        self.Baglan.setObjectName("Baglan")
        self.baglantiyikes = QtWidgets.QPushButton(self.groupBox)
        self.baglantiyikes.setGeometry(QtCore.QRect(30, 140, 421, 23))
        self.baglantiyikes.setObjectName("baglantiyikes")
        self.ComState = QtWidgets.QLabel(self.groupBox)
        self.ComState.setGeometry(QtCore.QRect(36, 170, 411, 21))
        self.ComState.setObjectName("ComState")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 230, 541, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 511, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Led1Yak = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Led1Yak.setObjectName("Led1Yak")
        self.horizontalLayout.addWidget(self.Led1Yak)
        self.Led1Sondur = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Led1Sondur.setObjectName("Led1Sondur")
        self.horizontalLayout.addWidget(self.Led1Sondur)
        self.baslik = QtWidgets.QLabel(self.centralwidget)
        self.baslik.setGeometry(QtCore.QRect(630, 0, 371, 21))
        self.baslik.setObjectName("baslik")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 20, 501, 341))
        self.groupBox_3.setObjectName("groupBox_3")
        self.MessageKutusu = QtWidgets.QTextEdit(self.groupBox_3)
        self.MessageKutusu.setGeometry(QtCore.QRect(13, 20, 481, 311))
        self.MessageKutusu.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 21))
        self.menubar.setMouseTracking(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ARDUİNO LED ÇALIŞMASI"))
        self.groupBox.setTitle(_translate("MainWindow", "preparation"))
        self.Baglan.setText(_translate("MainWindow", "BAĞLAN"))
        self.baglantiyikes.setText(_translate("MainWindow", "BAĞLANTIYI KES"))
        self.ComState.setText(_translate("MainWindow", "..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "Controller"))
        self.Led1Yak.setText(_translate("MainWindow", "LED 1 YAK"))
        self.Led1Sondur.setText(_translate("MainWindow", "LED 2 SÖNDÜR"))
        self.baslik.setText(_translate("MainWindow", "Seri Port Haberleşme KUTUSU"))
        self.groupBox_3.setTitle(_translate("MainWindow", "HUMA AR-GE"))
